### ISSUE TITLE
Support externalizing links with vanity paths

### ISSUE THREAD

**Issue by royteeuwen** [wcm-io/io.wcm.handler.link#12]
I'm trying to read through all the specific docs / OSGi configs etc, but I don't think it's currently possible to externalize an URL with the vanity path used in the final externalized URL (like is done by setting the vanityConfig i the PathProcessor in the AEM components Link classes). Am I correct in this, or might I be missing something?

**Comment by royteeuwen** [comment]
Is blocked by the mentioned issue

**Comment by royteeuwen** [comment]
super, thanks @stefanseifert . Any idea when you could make a release for this and the url dependency?

**Comment by stefanseifert** [comment]
will do it this week
