### ISSUE TITLE
On drag and drop of new component Link Tab title is showing mandatory icon beside title.

### ISSUE THREAD

**Issue by srigurram7792** [wcm-io/io.wcm.handler.link#16]
We are using wcm-io/handler/link/components/granite/form/linkRefContainer in our project, if we keep required= true for the link ref node and try to drop new component that contains this linkref. 

Expected: validation only done after editor trying to submit the dialog

Actual: The tab title is pre populated with mandatory error icon besides the tab title

CC @stefanseifert

**Comment by stefanseifert** [comment]
i was not able to reproduce the problem with our sample application, i created a branch which marks the link as required as described in your use case: https://github.com/wcm-io/io.wcm.samples/tree/experimental/make-link-required

then i tried to reproduce the problem with these steps:
* deploy the application to locale AEMaaCS SDK
* on the homepage http://localhost:4502/editor.html/content/wcm-io-samples/en.html add a new "Stage Header Link Item" component in the stage header component (below "Submit paper" example link)
* open the edit dialog of the newly created component

it shows * for the required link title and link, but no validation error - this is only shown when trying the save the edit dialog.

**Comment by srigurram7792** [comment]
Many thank for the message, Apparently the issue is happening because we use custom link types in the project which in-turn trigger this mandatory check. If I remove this custom link types with the default link types the doesn't exist. At least now we are sure that issue doesn't come from wcm.io and we will take it further from here.

**Comment by stefanseifert** [comment]
thanks for the confirmation!
